--
-- PostgreSQL database dump
--


--.__      .___             __     __                          .__                      __                               .__        __                   __                                    .__         .______.    
--|__|   __| _/____   _____/  |_  |  | __ ____   ______  _  __ |  |__   ______  _  __ _/  |_  ____     ______ ___________|__|______/  |_  ______   _____/  |_  ___________   ____   ___________|  |      __| _/\_ |__  
--|  |  / __ |/  _ \ /    \   __\ |  |/ //    \ /  _ \ \/ \/ / |  |  \ /  _ \ \/ \/ / \   __\/  _ \   /  ___// ___\_  __ \  \____ \   __\ \____ \ /  _ \   __\/ ___\_  __ \_/ __ \ /  ___/ ____/  |     / __ |  | __ \ 
--|  | / /_/ (  <_> )   |  \  |   |    <|   |  (  <_> )     /  |   Y  (  <_> )     /   |  | (  <_> )  \___ \\  \___|  | \/  |  |_> >  |   |  |_> >  <_> )  | / /_/  >  | \/\  ___/ \___ < <_|  |  |__  / /_/ |  | \_\ \
--|__| \____ |\____/|___|  /__|   |__|_ \___|  /\____/ \/\_/   |___|  /\____/ \/\_/    |__|  \____/  /____  >\___  >__|  |__|   __/|__|   |   __/ \____/|__| \___  /|__|    \___  >____  >__   |____/  \____ |  |___  /
--          \/           \/            \/    \/                     \/                                    \/     \/         |__|          |__|              /_____/             \/     \/   |__|            \/      \/ 

\restrict 311ZYVhuUEeYPRushN2VOheZ0sSlPhVXOxLUiBBV1UCfK0BRmvhRBoLglC6kq1k

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-22 15:31:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(100) NOT NULL
);


ALTER TABLE public.company OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16398)
-- Name: operationalAreas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."operationalAreas" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    "companyId" bigint NOT NULL
);


ALTER TABLE public."operationalAreas" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16412)
-- Name: operationalAreas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."operationalAreas" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."operationalAreas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16413)
-- Name: prompts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prompts (
    id bigint NOT NULL,
    "promptText" character varying(2000) NOT NULL,
    "areaId" bigint NOT NULL
);


ALTER TABLE public.prompts OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16428)
-- Name: prompts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prompts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prompts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5021 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company (id, name, password) FROM stdin;
0	pepe SRL	hardPassword1234
1	Timba SA	letsGoGambling
\.


--
-- TOC entry 5023 (class 0 OID 16398)
-- Dependencies: 221
-- Data for Name: operationalAreas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."operationalAreas" (id, name, password, "companyId") FROM stdin;
1	IT	fuckHR	0
2	HR	live_laugh_love	0
3	I+D	password	0
\.


--
-- TOC entry 5025 (class 0 OID 16413)
-- Dependencies: 223
-- Data for Name: prompts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prompts (id, "promptText", "areaId") FROM stdin;
1	how to print in black and white without pink ink	2
\.


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 220
-- Name: company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.company_id_seq', 1, false);


--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 222
-- Name: operationalAreas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."operationalAreas_id_seq"', 3, true);


--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 224
-- Name: prompts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prompts_id_seq', 1, true);


--
-- TOC entry 4867 (class 2606 OID 16396)
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- TOC entry 4869 (class 2606 OID 16406)
-- Name: operationalAreas operationalAreas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."operationalAreas"
    ADD CONSTRAINT "operationalAreas_pkey" PRIMARY KEY (id);


--
-- TOC entry 4871 (class 2606 OID 16422)
-- Name: prompts prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prompts
    ADD CONSTRAINT prompts_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 16407)
-- Name: operationalAreas operationalAreas_companyId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."operationalAreas"
    ADD CONSTRAINT "operationalAreas_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES public.company(id);


--
-- TOC entry 4873 (class 2606 OID 16423)
-- Name: prompts prompts_areaId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prompts
    ADD CONSTRAINT "prompts_areaId_fkey" FOREIGN KEY ("areaId") REFERENCES public."operationalAreas"(id);


-- Completed on 2026-03-22 15:31:51

--
-- PostgreSQL database dump complete
--

\unrestrict 311ZYVhuUEeYPRushN2VOheZ0sSlPhVXOxLUiBBV1UCfK0BRmvhRBoLglC6kq1k

