--*hice el backup como un plain.

--
-- PostgreSQL database dump
--

\restrict Y2pwg3DJ3rEmz5vRl5vv5RXmz9oGPRr5bH8ok43CNdueom2Vm4R58s2fj791apc

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-30 17:15:18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(100) NOT NULL
);


ALTER TABLE public.company OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16398)
-- Name: operationalAreas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."operationalAreas" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    "companyId" bigint NOT NULL
);


ALTER TABLE public."operationalAreas" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16412)
-- Name: operationalAreas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."operationalAreas" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."operationalAreas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16413)
-- Name: prompts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prompts (
    id bigint NOT NULL,
    "promptText" character varying(2000) NOT NULL,
    "areaId" bigint NOT NULL
);


ALTER TABLE public.prompts OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16428)
-- Name: prompts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prompts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prompts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5023 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company (id, name, password) FROM stdin;
0	pepe SRL	$2b$10$W5wgL/P2Y30xD9rw7hy.L.wf1yCvhHm1y2aI9JpSMYUm6LCB8P6a2
1	Timba SA	$2b$10$RWyBj2zyU7brLkbNqAPZs.CYBAo.1QfGnQVo6KekBABxXlXGrIT9W
2	prueba	$2b$10$HYLsLO6/vaOOvg4.OlCZl.LE5CD0XGcfpz41otCaBqAD/S7mIyUS.
3	Insecurity LLC	$2b$10$m.zaIhudaJgiQ0fZmNBmE.jo.spJMSsQBcB62wOB/Ql/2MrGhxtlG
\.


--
-- TOC entry 5025 (class 0 OID 16398)
-- Dependencies: 221
-- Data for Name: operationalAreas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."operationalAreas" (id, name, password, "companyId") FROM stdin;
3	I+D	$2b$10$focy4YNwzlc38QA7YJilZeL9nQhIzQJX.Zi6s3GPvTyp9lvdinGJe	0
1	IT	$2b$10$oJoFtiLKEarVMOrxjV/3U.sR2egaXtbyUG/3sJn8KvlIsOuqPHZjO	0
2	HR	$2b$10$HyFnUGXoIAImqm9YfjUICODziCkubEV0.1L0YyRhiP2I8hSh9YIOu	0
\.


--
-- TOC entry 5027 (class 0 OID 16413)
-- Dependencies: 223
-- Data for Name: prompts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prompts (id, "promptText", "areaId") FROM stdin;
1	how to print in black and white without pink ink	2
\.


--
-- TOC entry 5041 (class 0 OID 0)
-- Dependencies: 220
-- Name: company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.company_id_seq', 3, true);


--
-- TOC entry 5042 (class 0 OID 0)
-- Dependencies: 222
-- Name: operationalAreas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."operationalAreas_id_seq"', 3, true);


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 224
-- Name: prompts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prompts_id_seq', 1, true);


--
-- TOC entry 4867 (class 2606 OID 16396)
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- TOC entry 4871 (class 2606 OID 16406)
-- Name: operationalAreas operationalAreas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."operationalAreas"
    ADD CONSTRAINT "operationalAreas_pkey" PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 16422)
-- Name: prompts prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prompts
    ADD CONSTRAINT prompts_pkey PRIMARY KEY (id);


--
-- TOC entry 4869 (class 2606 OID 16433)
-- Name: company unique_ company_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT "unique_ company_name" UNIQUE (name);


--
-- TOC entry 4874 (class 2606 OID 16407)
-- Name: operationalAreas operationalAreas_companyId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."operationalAreas"
    ADD CONSTRAINT "operationalAreas_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES public.company(id);


--
-- TOC entry 4875 (class 2606 OID 16423)
-- Name: prompts prompts_areaId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prompts
    ADD CONSTRAINT "prompts_areaId_fkey" FOREIGN KEY ("areaId") REFERENCES public."operationalAreas"(id);


--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO "dbToAPI_user";


--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE company; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.company TO "dbToAPI_user";


--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 220
-- Name: SEQUENCE company_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.company_id_seq TO "dbToAPI_user";


--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE "operationalAreas"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public."operationalAreas" TO "dbToAPI_user";


--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 222
-- Name: SEQUENCE "operationalAreas_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."operationalAreas_id_seq" TO "dbToAPI_user";


--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE prompts; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.prompts TO "dbToAPI_user";


--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 224
-- Name: SEQUENCE prompts_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.prompts_id_seq TO "dbToAPI_user";


-- Completed on 2026-03-30 17:15:18

--
-- PostgreSQL database dump complete
--

\unrestrict Y2pwg3DJ3rEmz5vRl5vv5RXmz9oGPRr5bH8ok43CNdueom2Vm4R58s2fj791apc

