
### test token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTc3ODA5MDQ5NiwiZXhwIjoxNzc4MDk0MDk2fQ.ig5N5E4vpHayt0bv3PwY3NCyYhyIy1kJt2QJEnRbkUc
### employee test token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInVzZXJuYW1lIjoidGVzdEVtcGxveWVlIiwiaWF0IjoxNzc4MDkwNTc0LCJleHAiOjE3NzgwOTQxNzR9.30tutfoWDg2gfaC3swu2HZx-SG7bTFJet6UxgHncRUI
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJNaWNoYWVsU2NvdHQiLCJpYXQiOjE3NzgwOTAwNzgsImV4cCI6MTc3ODA5MzY3OH0.0sUWWmwxdXMiomTGTWJsPI05K58XR4jeoOopZWlmDEo
POST http://localhost:3000/api/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInVzZXJuYW1lIjoidGVzdEVtcGxveWVlIiwiaWF0IjoxNzc4MDk0ODA1LCJleHAiOjE3NzgwOTg0MDV9.sJpfWkUzejLYtV4bmqtioFRpgeX98w3OppjbTC4WqQY
Content-Type: application/json

{
    "email": "michaelscott@gmail.com",
    "password": "password"
}
###
PUT http://localhost:3000/api/user
Content-Type: application/json

{
    "email": "testingsession@hotmail.com",
    "password": "this_is_the_password",
    "name": "this_is_the_password"
}

###
POST http://localhost:3000/api/message
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJWbGFkIFVsaWFub3YiLCJpYXQiOjE3Nzc2NjE3NTksImV4cCI6MTc3NzY2NTM1OX0.MXFvD0mLjQJEFzlOgKVDNKiSdS_nVK9-WUGDzLsIjc4
Content-Type: application/json

{
    "message": "proletariat of the world, unite!",
    "sender": "gemini"
}


###notyourbusiness@gmail.com: airplane tree dog window
###michaelscott@gmail.com: password (?)
###thepeoplesparty@gmail.com: workers of the world unite
###2gulag@siberia.ru: t-34


