
### test token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTc3ODA5MDQ5NiwiZXhwIjoxNzc4MDk0MDk2fQ.ig5N5E4vpHayt0bv3PwY3NCyYhyIy1kJt2QJEnRbkUc
### employee test token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInVzZXJuYW1lIjoidGVzdEVtcGxveWVlIiwiaWF0IjoxNzc4MDkwNTc0LCJleHAiOjE3NzgwOTQxNzR9.30tutfoWDg2gfaC3swu2HZx-SG7bTFJet6UxgHncRUI
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJNaWNoYWVsU2NvdHQiLCJpYXQiOjE3NzgwOTAwNzgsImV4cCI6MTc3ODA5MzY3OH0.0sUWWmwxdXMiomTGTWJsPI05K58XR4jeoOopZWlmDEo
GET http://localhost:3000/api/statsAvg
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJNaWNoYWVsU2NvdHQiLCJpYXQiOjE3NzkxMTQ1MDcsImV4cCI6MTc3OTExODEwN30.uALCH2EucNgN039UBifeTeWIbrLlvXBaAnXhYNFpfjU
###
POST http://localhost:3000/api/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInVzZXJuYW1lIjoidGVzdEVtcGxveWVlIiwiaWF0IjoxNzc4MDk0ODA1LCJleHAiOjE3NzgwOTg0MDV9.sJpfWkUzejLYtV4bmqtioFRpgeX98w3OppjbTC4WqQY
Content-Type: application/json

{
    "email": "michaelscott@gmail.com",
    "companyId": "password"
}

###
POST http://localhost:3000/api/login
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInVzZXJuYW1lIjoidGVzdEVtcGxveWVlIiwiaWF0IjoxNzc4MDk0ODA1LCJleHAiOjE3NzgwOTg0MDV9.sJpfWkUzejLYtV4bmqtioFRpgeX98w3OppjbTC4WqQY
Content-Type: application/json

{
    "email": "michaelscott@gmail.com",
    "password": "password"
}
###
PATCH http://localhost:3000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJ0aGlzX2lzX3RoZV9wYXNzd29yZCIsImVtYWlsIjoidGVzdGluZ3Nlc3Npb25AaG90bWFpbC5jb20iLCJhbGxvd2VkX2FpcyI6IntjaGF0Z3B0LGNsYXVkZSxnZW1pbmksb3RoZXJ9IiwiaWF0IjoxNzc5MDQ5MzU4LCJleHAiOjE3NzkwNTI5NTh9.tnpqUtTqXBNl-mVhUWQTG36_cH2qItVkfl029Na5HCQ
Content-Type: application/json

{
    "email": "this_is_the_password",
    "name": "updated_name_again!"
}

###
POST http://localhost:3000/api/message
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJWbGFkIFVsaWFub3YiLCJpYXQiOjE3Nzc2NjE3NTksImV4cCI6MTc3NzY2NTM1OX0.MXFvD0mLjQJEFzlOgKVDNKiSdS_nVK9-WUGDzLsIjc4
Content-Type: application/json

{
    "message": "proletariat of the world, unite!",
    "sender": "gemini"
}


###notyourbusiness@gmail.com: airplane tree dog window
###michaelscott@gmail.com: password (?)
###thepeoplesparty@gmail.com: workers of the world unite
###2gulag@siberia.ru: t-34


