name: Push to Hugging Face Spaces

on:
  push:
    branches:
      - Elian
    # El workflow solo se dispara si hay cambios reales dentro de la carpeta de la API
    paths:
      - 'API/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Es obligatorio para que git subtree pueda calcular el historial

      - name: Push a Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configuramos un usuario temporal de Git para evitar conflictos en el entorno virtual
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Añadimos el repositorio remoto de Hugging Face
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/datascope26/datascope-api
          
          # Extrae SOLO el contenido de la carpeta API y lo empuja con fuerza al main de Hugging Face
          git subtree push --prefix API hf main