name: Push to Hugging Face Spaces

on:
  push:
    branches:
      - Elian
    paths:
      - 'API/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push a Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/datascope26/datascope-api
          
          git subtree split --prefix API -b deploy-branch
          
          git push hf deploy-branch:main --force